Add rust project URLS
mozilla/moz-handler pull request #6
Opened 2017-01-19 16:20 UTC by skade

👋

2017-01-19 18:29 UTC, Hoverbear requested changes
Please add https://servo.org/ :)

2017-01-19 22:05 UTC, skade commented
@Hoverbear see https://github.com/mozilla/moz-handler/pull/6/commits/8ca969193e1c4bc29060c59ec3302f3e235d0fbd

2017-01-20 06:33 UTC, Hoverbear approved these changes

2017-01-23 20:14 UTC, mykmelez commented
Sorry for the delay responding! My GitHub account wasn't "following" the repo, even though I created it, so I didn't get notified about the request. LGTM! I only made two changes while resolving conflicts:
* removed the trailing slash from the URL for *rust-community*, since I noticed that `https://community.rs/` was redirecting to `https://community.rs`.
* added a trailing comma to the entry for *servo* to avoid the need to add it when appending the next entry to the list

2017-01-23 20:14 UTC, merged